// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sojcdnljapfllnltgxfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvamNkbmxqYXBmbGxubHRneGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzNjg3MDksImV4cCI6MjA4Njk0NDcwOX0.M5o2gjveZUTzSguk8z_kMR3ebLq9gxxq007B_i4ZYLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});